### ISSUE TITLE
docker compose build completed but have error in immich server

### ISSUE THREAD

**Issue by docfactory37** [alextran1502/immich#119]
**To Reproduce**
1. completed a docker .env file update
2. completed a docker copose build
3. all items are runing but i get a error on the immich server see screenshot below
 
![image](https://user-images.githubusercontent.com/20963053/162126694-c9d68e03-b592-4c97-9d3d-bf996e11d2be.png)

Not sure what JWT_SECRET should have not able to fine anything in the doc

**Comment by docfactory37** [comment]
i have been able to get pas the above issue but add a random string but now i get the below when i try and access the server by the nginx 

when i go to http://<server-IP>:2283/ i get the below

![image](https://user-images.githubusercontent.com/20963053/162129996-ffe3474e-b892-4f55-942b-b76d2eb34566.png)

**Comment by alextran1502** [comment]
You will need the mobile app. There is no web interface for this application. 🙂

**Comment by docfactory37** [comment]
O well that explains that 🙂 is there plans for one to be added / created?

**Comment by alextran1502** [comment]
Yes, I do have a plan for the web interface.

It is not working in the background. It is quite challenging since Apple and Android have made effort to reduce the scope of what applications can do in the background to prevent them from "spying" on the users. But I think I found a potential solution, it is on the low priority though, so it might get implemented sometime in the future :) 

I am glad it is working for you! Please open a new issue if you have any further questions.
