### ISSUE TITLE
No matching manifest for linux/arm64/v8

### ISSUE THREAD

**Issue by datsoy** [alextran1502/immich#135]
Throws a "no matching manifest for linux/arm64/v8 in the manifest list entries" when I try to run on my arm oracle vps.

![Screenshot_20220430-150614112 (1)](https://user-images.githubusercontent.com/67457715/166096075-09248cd2-5ee6-42dc-a20e-2638ca31134e.jpg)

**Comment by alextran1502** [comment]
This is the correct behavior since I didn't have this architecture built on Dockerhub. Can you please try 

```bash
docker-compose -f ./docker/docker-compose.dev.yml up --build -V --remove-orphans
```

I assume there will be an issue with the microservices service since Tensorflow doesn't fully support Arm-based architecture. If so, you can just comment out the microservices service in the `docker-compose.dev.yml` file

**Comment by datsoy** [comment]
I see, thank you.

It did build and deploy immich after commenting out microservices, but failed to access the server. Maybe its oracle's firewall, is their any port should I open aside from 2883? udp&tcp?

**Comment by alextran1502** [comment]
Can you check if you open the port correctly, it is 2283 not 2883

**Comment by datsoy** [comment]
Yup, I opened wrong port. Haha. 😅
Its working now, gonna try and test it.
Thanks.

**Comment by jschwalbe** [comment]
Would you be able to easily add this to Dockerhub?
