### ISSUE TITLE
about MapBox not work ! 

### ISSUE THREAD

**Issue by League2EB** [alextran1502/immich#138]
I went to [MapBox](https://www.mapbox.com/) to register

When I fill in the following two fields, and restart docker-compose
I don't see any effect in the iOS Application

```shell
ENABLE_MAPBOX=true
MAPBOX_KEY=token
```

Is the value of MAPBOX_KEY the token in the picture?

thx all ! 

![image](https://s2.loli.net/2022/05/03/C7SGUvRYtDN13QZ.png)

**Comment by alextran1502** [comment]
The token is correct, you have to have the mapbox enabled before upload photos or videos to the server. 

The mapbox operation is on the server side, it is used to get the city, state from the asset's coordinates (this process is called reverse geocoding) so that you can search by city or state. 

In your case, you can try access the Postgres database and delete all rows in the assets table, or simply spin up a new user and create then perform the backup process again.

**Comment by League2EB** [comment]
Thank you very much for your assistance. The problem has been solved.
